/*
 * ViewerPanel.java
 *
 * Created on 4. Februar 2007, 01:03
 */

package org.jcurl.demo.viewer;

import org.jcurl.core.swing.Zoomer;

/**
 *
 * @author  m
 */
public class ViewerPanel extends javax.swing.JPanel {
    
    /** Creates new form ViewerPanel */
    public ViewerPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        org.jcurl.core.swing.PositionDisplay birdsEyeDisplay;
        javax.swing.JPanel buttonPanel;
        javax.swing.JPanel controlPanel;
        org.jcurl.core.swing.JCurlDisplay detailDisplay;
        javax.swing.JPanel detailPanel;
        javax.swing.JButton pauseButton;
        javax.swing.JButton startButton;
        javax.swing.JButton stopButton;
        javax.swing.JSlider timeSlider;

        detailPanel = new javax.swing.JPanel();
        detailDisplay = new org.jcurl.core.swing.JCurlDisplay();
        birdsEyeDisplay = new org.jcurl.core.swing.PositionDisplay();
        controlPanel = new javax.swing.JPanel();
        timeSlider = new javax.swing.JSlider();
        buttonPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();

        detailPanel.setPreferredSize(new java.awt.Dimension(207, 200));
        detailDisplay.setZoom(Zoomer.HOUSE);

        org.jdesktop.layout.GroupLayout detailPanelLayout = new org.jdesktop.layout.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detailDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 412, Short.MAX_VALUE)
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detailDisplay, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        birdsEyeDisplay.setZoom(Zoomer.HOG2HACK);

        controlPanel.setLayout(new javax.swing.BoxLayout(controlPanel, javax.swing.BoxLayout.Y_AXIS));

        controlPanel.add(timeSlider);

        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.X_AXIS));

        startButton.setText("Start");
        buttonPanel.add(startButton);

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        buttonPanel.add(stopButton);

        pauseButton.setText("Pause");
        pauseButton.setEnabled(false);
        buttonPanel.add(pauseButton);

        controlPanel.add(buttonPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(controlPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(detailPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 412, Short.MAX_VALUE)
            .add(birdsEyeDisplay, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(detailPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(birdsEyeDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(controlPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
