/*
 * TacticsNB.java
 *
 * Created on 31. Januar 2007, 01:24
 */

package org.jcurl.demo.tactics;

import org.jcurl.core.model.FixpointZoomer;
import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;

/**
 * 
 * @author m
 */
public class TacticsNB extends javax.swing.JFrame {

    private static final long serialVersionUID = -2659368999064098936L;

    /** Creates new form TacticsNB */
    public TacticsNB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JDialog aboutDialog;
        javax.swing.JMenuItem aboutMenuItem;
        javax.swing.JLabel broomLabel;
        javax.swing.JPanel broomPanel;
        javax.swing.JSlider broomSlider;
        javax.swing.JTextField broomText;
        javax.swing.JPanel completePanel;
        javax.swing.JTabbedPane controlTabbedPane;
        javax.swing.JLabel curlLabel;
        javax.swing.JPanel curlPanel;
        javax.swing.JSlider curlSlider;
        javax.swing.JTextField curlText;
        javax.swing.JLabel drawToTeeLabel;
        javax.swing.JPanel drawToTeePanel;
        javax.swing.JSlider drawToTeeSlider;
        javax.swing.JTextField drawToTeeText;
        javax.swing.JMenuItem exitMenuItem;
        javax.swing.JMenuItem exportPngMenuItem;
        javax.swing.JMenu fileMenu;
        javax.swing.JMenu helpMenu;
        javax.swing.JPanel iceTab;
        javax.swing.JMenuBar jMenuBar1;
        javax.swing.JSeparator jSeparator1;
        javax.swing.JSeparator jSeparator2;
        javax.swing.JMenuItem loadMenuItem;
        javax.swing.JMenuItem newMenuItem;
        org.jcurl.core.swing.PositionDisplay overviewDisplay;
        javax.swing.JPanel rockTab;
        org.jcurl.core.swing.PositionDisplay rocksEditDisplay;
        javax.swing.JMenuItem saveAsMenuItem;
        javax.swing.JMenuItem saveMenuItem;
        javax.swing.JLabel splitLabel;
        javax.swing.JSlider splitSlider;
        javax.swing.JTextField splitText;
        javax.swing.JPanel timePanel;

        aboutDialog = new javax.swing.JDialog();
        completePanel = new javax.swing.JPanel();
        rocksEditDisplay = new org.jcurl.core.swing.PositionDisplay();
        controlTabbedPane = new javax.swing.JTabbedPane();
        rockTab = new javax.swing.JPanel();
        broomPanel = new javax.swing.JPanel();
        broomLabel = new javax.swing.JLabel();
        broomSlider = new javax.swing.JSlider();
        broomText = new javax.swing.JTextField();
        timePanel = new javax.swing.JPanel();
        splitLabel = new javax.swing.JLabel();
        splitSlider = new javax.swing.JSlider();
        splitText = new javax.swing.JTextField();
        iceTab = new javax.swing.JPanel();
        curlPanel = new javax.swing.JPanel();
        curlLabel = new javax.swing.JLabel();
        curlSlider = new javax.swing.JSlider();
        curlText = new javax.swing.JTextField();
        drawToTeePanel = new javax.swing.JPanel();
        drawToTeeLabel = new javax.swing.JLabel();
        drawToTeeSlider = new javax.swing.JSlider();
        drawToTeeText = new javax.swing.JTextField();
        overviewDisplay = new org.jcurl.core.swing.PositionDisplay();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        loadMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exportPngMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        GroupLayout aboutDialogLayout = new GroupLayout(aboutDialog
                .getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(aboutDialogLayout
                .createParallelGroup(GroupLayout.LEADING).add(0, 264,
                        Short.MAX_VALUE));
        aboutDialogLayout.setVerticalGroup(aboutDialogLayout
                .createParallelGroup(GroupLayout.LEADING).add(0, 169,
                        Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JCurl Tactics Demo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        completePanel.setBackground(new java.awt.Color(255, 255, 204));
        completePanel.setMinimumSize(new java.awt.Dimension(300, 150));
        rocksEditDisplay.setName("The Rocks");

        rockTab.setBackground(new java.awt.Color(255, 204, 102));
        rockTab.setName("Rock");
        broomPanel.setOpaque(false);
        broomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        broomLabel.setText("Broom");

        broomSlider.setMajorTickSpacing(1000);
        broomSlider.setMaximum(2000);
        broomSlider.setMinimum(-2000);
        broomSlider.setMinorTickSpacing(100);
        broomSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        broomSlider.setPaintLabels(true);
        broomSlider.setPaintTicks(true);
        broomSlider.setOpaque(false);

        broomText.setText("jTextField1");

        GroupLayout broomPanelLayout = new GroupLayout(broomPanel);
        broomPanel.setLayout(broomPanelLayout);
        broomPanelLayout.setHorizontalGroup(broomPanelLayout
                .createParallelGroup(GroupLayout.LEADING).add(broomLabel,
                        GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE).add(
                        broomText, GroupLayout.DEFAULT_SIZE, 77,
                        Short.MAX_VALUE).add(broomSlider,
                        GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE));
        broomPanelLayout.setVerticalGroup(broomPanelLayout.createParallelGroup(
                GroupLayout.LEADING).add(
                GroupLayout.TRAILING,
                broomPanelLayout.createSequentialGroup().add(broomLabel)
                        .addPreferredGap(LayoutStyle.RELATED).add(broomSlider,
                                GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.RELATED).add(broomText,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)));

        timePanel.setOpaque(false);
        splitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        splitLabel.setText("SplitTime");

        splitSlider.setMajorTickSpacing(1000);
        splitSlider.setMaximum(2500);
        splitSlider.setMinimum(500);
        splitSlider.setMinorTickSpacing(100);
        splitSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        splitSlider.setPaintLabels(true);
        splitSlider.setPaintTicks(true);
        splitSlider.setOpaque(false);

        splitText.setText("jTextField1");

        GroupLayout timePanelLayout = new GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(timePanelLayout.createParallelGroup(
                GroupLayout.LEADING).add(splitText, GroupLayout.DEFAULT_SIZE,
                82, Short.MAX_VALUE).add(splitSlider, GroupLayout.DEFAULT_SIZE,
                82, Short.MAX_VALUE).add(splitLabel, GroupLayout.DEFAULT_SIZE,
                82, Short.MAX_VALUE));
        timePanelLayout.setVerticalGroup(timePanelLayout.createParallelGroup(
                GroupLayout.LEADING).add(
                timePanelLayout.createSequentialGroup().add(splitLabel).add(7,
                        7, 7).add(splitSlider, GroupLayout.DEFAULT_SIZE, 105,
                        Short.MAX_VALUE).addPreferredGap(LayoutStyle.RELATED)
                        .add(splitText, GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)));

        GroupLayout rockTabLayout = new GroupLayout(rockTab);
        rockTab.setLayout(rockTabLayout);
        rockTabLayout.setHorizontalGroup(rockTabLayout.createParallelGroup(
                GroupLayout.LEADING).add(
                GroupLayout.TRAILING,
                rockTabLayout.createSequentialGroup().add(broomPanel,
                        GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE).addPreferredGap(LayoutStyle.RELATED)
                        .add(timePanel, GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)));
        rockTabLayout.setVerticalGroup(rockTabLayout.createParallelGroup(
                GroupLayout.LEADING).add(timePanel, GroupLayout.DEFAULT_SIZE,
                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(broomPanel,
                GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
        controlTabbedPane.addTab("Rock", null, rockTab,
                "Broom Position (meters)");

        iceTab.setBackground(new java.awt.Color(153, 204, 255));
        iceTab.setDoubleBuffered(false);
        iceTab.setName("Rock");
        curlPanel.setDoubleBuffered(false);
        curlPanel.setOpaque(false);
        curlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curlLabel.setText("Curl");

        curlSlider.setMajorTickSpacing(1000);
        curlSlider.setMaximum(5000);
        curlSlider.setMinorTickSpacing(100);
        curlSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        curlSlider.setPaintLabels(true);
        curlSlider.setPaintTicks(true);
        curlSlider.setOpaque(false);

        curlText.setText("jTextField1");

        GroupLayout curlPanelLayout = new GroupLayout(curlPanel);
        curlPanel.setLayout(curlPanelLayout);
        curlPanelLayout.setHorizontalGroup(curlPanelLayout.createParallelGroup(
                GroupLayout.LEADING).add(curlLabel, GroupLayout.DEFAULT_SIZE,
                76, Short.MAX_VALUE).add(curlText, GroupLayout.DEFAULT_SIZE,
                76, Short.MAX_VALUE).add(curlSlider, GroupLayout.DEFAULT_SIZE,
                76, Short.MAX_VALUE));
        curlPanelLayout.setVerticalGroup(curlPanelLayout.createParallelGroup(
                GroupLayout.LEADING).add(
                GroupLayout.TRAILING,
                curlPanelLayout.createSequentialGroup().add(curlLabel)
                        .addPreferredGap(LayoutStyle.RELATED).add(curlSlider,
                                GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.RELATED).add(curlText,
                                GroupLayout.DEFAULT_SIZE, 76,
                                GroupLayout.PREFERRED_SIZE)));

        drawToTeePanel.setDoubleBuffered(false);
        drawToTeePanel.setOpaque(false);
        drawToTeeLabel
                .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        drawToTeeLabel.setText("DrawToTee");
        drawToTeeLabel.setMaximumSize(new java.awt.Dimension(70, 15));
        drawToTeeLabel.setMinimumSize(new java.awt.Dimension(70, 15));

        drawToTeeSlider.setMajorTickSpacing(5000);
        drawToTeeSlider.setMaximum(30000);
        drawToTeeSlider.setMinimum(15000);
        drawToTeeSlider.setMinorTickSpacing(1000);
        drawToTeeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        drawToTeeSlider.setPaintLabels(true);
        drawToTeeSlider.setPaintTicks(true);
        drawToTeeSlider.setOpaque(false);

        drawToTeeText.setText("jTextField1");

        GroupLayout drawToTeePanelLayout = new GroupLayout(drawToTeePanel);
        drawToTeePanel.setLayout(drawToTeePanelLayout);
        drawToTeePanelLayout.setHorizontalGroup(drawToTeePanelLayout
                .createParallelGroup(GroupLayout.LEADING).add(drawToTeeLabel,
                        GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE).add(
                        drawToTeeSlider, GroupLayout.DEFAULT_SIZE, 79,
                        Short.MAX_VALUE).add(drawToTeeText,
                        GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE));
        drawToTeePanelLayout.setVerticalGroup(drawToTeePanelLayout
                .createParallelGroup(GroupLayout.LEADING).add(
                        drawToTeePanelLayout.createSequentialGroup().add(
                                drawToTeeLabel, GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE).add(7, 7, 7).add(
                                drawToTeeSlider, GroupLayout.DEFAULT_SIZE, 105,
                                Short.MAX_VALUE).addPreferredGap(
                                LayoutStyle.RELATED).add(drawToTeeText,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)));

        GroupLayout iceTabLayout = new GroupLayout(iceTab);
        iceTab.setLayout(iceTabLayout);
        iceTabLayout.setHorizontalGroup(iceTabLayout.createParallelGroup(
                GroupLayout.LEADING).add(
                iceTabLayout.createSequentialGroup().add(curlPanel,
                        GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE).addPreferredGap(
                        LayoutStyle.RELATED, 10, Short.MAX_VALUE).add(
                        drawToTeePanel, GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)));
        iceTabLayout.setVerticalGroup(iceTabLayout.createParallelGroup(
                GroupLayout.LEADING).add(curlPanel, GroupLayout.DEFAULT_SIZE,
                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(drawToTeePanel,
                GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
        controlTabbedPane.addTab("IceSize", iceTab);

        GroupLayout completePanelLayout = new GroupLayout(completePanel);
        completePanel.setLayout(completePanelLayout);
        completePanelLayout.setHorizontalGroup(completePanelLayout
                .createParallelGroup(GroupLayout.LEADING).add(
                        GroupLayout.TRAILING,
                        completePanelLayout.createSequentialGroup().add(
                                rocksEditDisplay, GroupLayout.PREFERRED_SIZE,
                                149, Short.MAX_VALUE).addPreferredGap(
                                LayoutStyle.RELATED).add(controlTabbedPane,
                                GroupLayout.PREFERRED_SIZE, 170,
                                GroupLayout.PREFERRED_SIZE)));
        completePanelLayout.setVerticalGroup(completePanelLayout
                .createParallelGroup(GroupLayout.LEADING).add(rocksEditDisplay,
                        GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE).add(
                        controlTabbedPane, GroupLayout.DEFAULT_SIZE, 179,
                        Short.MAX_VALUE));

        overviewDisplay.setZoom(FixpointZoomer.HOG2HACK);

        fileMenu.setText("File");
        newMenuItem.setText("New");
        fileMenu.add(newMenuItem);

        loadMenuItem.setText("Load");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(loadMenuItem);

        fileMenu.add(jSeparator2);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As");
        fileMenu.add(saveAsMenuItem);

        exportPngMenuItem.setText("Export as Png");
        fileMenu.add(exportPngMenuItem);

        fileMenu.add(jSeparator1);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");
        helpMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                GroupLayout.LEADING).add(overviewDisplay,
                GroupLayout.PREFERRED_SIZE, 329, Short.MAX_VALUE).add(
                completePanel, GroupLayout.DEFAULT_SIZE,
                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.LEADING)
                .add(
                        GroupLayout.TRAILING,
                        layout.createSequentialGroup().add(completePanel,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).add(
                                2, 2, 2).add(overviewDisplay,
                                GroupLayout.PREFERRED_SIZE, 75,
                                GroupLayout.PREFERRED_SIZE)));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }// GEN-LAST:event_exitMenuItemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }// GEN-LAST:event_formWindowClosed

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loadMenuItemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_loadMenuItemActionPerformed

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TacticsNB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
