/*
 * NBForm.java
 *
 * Created on 6. Juni 2006, 23:09
 */

package org.jcurl.mr.exp.gui;

/**
 *
 * @author  m
 */
public class NBForm extends javax.swing.JPanel {
    
    /** Creates new form NBForm */
    public NBForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JLabel jLabel1;

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Hello, world!");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabel1, new java.awt.GridBagConstraints());

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
